import java.util.*;

public class Main_Category {

        public static void main(String[] args) {
            String[] categories = {
                    "Finance/Investing",
                    "News/Politics",
                    "Business & Industrial",
                    "Finance/Investing/Currencies & Foreign Exchange",
                    "Food & Drink/Beverages/Coffee & Tea",
                    "Sports/Team Sports/Soccer",
                    "People & Society/Social Issues & Advocacy",
                    "Computers & Electronics/Consumer Electronics/Audio Equipment",
                    "Health/Health Foundations & Medical Research",
                    "Computers & Electronics/Software/Operating Systems",
                    "Sensitive Subjects",
                    "Food & Drink/Beverages",
                    "Finance/Insurance",
                    "Finance/Credit & Lending/Loans",
                    "Food & Drink/Restaurants",
                    "Sports/Team Sports/Baseball",
                    "Arts & Entertainment/Movies",
                    "Arts & Entertainment/TV & Video/TV Shows & Programs",
                    "Home & Garden",
                    "Travel/Air Travel",
                    "Computers & Electronics",
                    "News/Business News/Company News",
                    "Food & Drink",
                    "Arts & Entertainment/Music & Audio",
                    "Autos & Vehicles/Motor Vehicles (By Type)",
                    "Business & Industrial/Pharmaceuticals & Biotech",
                    "Games",
                    "Games/Computer & Video Games",
                    "Sports/Motor Sports",
                    "Computers & Electronics/Computer Hardware/Computer Components",
                    "Finance/Accounting & Auditing",
                    "Finance/Investing/Stocks & Bonds",
                    "Sports/Individual Sports/Golf/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles",
                    "Shopping/Apparel/Footwear",
                    "Finance",
                    "Games/Computer & Video Games/Sandbox Games",
                    "Business & Industrial/Business Services",
                    "Reference/Humanities/History",
                    "Online Communities",
                    "Beauty & Fitness/Hair Care",
                    "Games/Card Games/Poker & Casino Games",
                    "Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife",
                    "Business & Industrial/Business Finance",
                    "Autos & Vehicles/Motor Vehicles (By Type)/Trucks & SUVs",
                    "Sports/Team Sports/Basketball",
                    "Finance/Investing/Commodities & Futures Trading",
                    "Business & Industrial/Energy & Utilities/Oil & Gas",
                    "Business & Industrial/Energy & Utilities",
                    "Law & Government/Legal/Legal Services",
                    "Sports/Fantasy Sports",
                    "Autos & Vehicles/Vehicle Parts & Services",
                    "News/Business News",
                    "Computers & Electronics/Electronics & Electrical/Electronic Components",
                    "News/Business News/Financial Markets News",
                    "Arts & Entertainment/Online Media",
                    "Books & Literature",
                    "Computers & Electronics/Consumer Electronics",
                    "Sports/Team Sports/Hockey",
                    "Health/Health Conditions/Diabetes",
                    "Health/Health Conditions/Infectious Diseases",
                    "People & Society",
                    "Computers & Electronics/Consumer Electronics/TV & Video Equipment",
                    "Hobbies & Leisure/Radio Control & Modeling",
                    "Autos & Vehicles",
                    "Sports",
                    "Business & Industrial/Metals & Mining",
                    "Travel/Cruises & Charters",
                    "Health",
                    "Finance/Banking",
                    "Computers & Electronics/Computer Hardware/Laptops & Notebooks",
                    "Computers & Electronics/Electronics & Electrical",
                    "Law & Government/Government",
                    "Health/Oral & Dental Care",
                    "Autos & Vehicles/Vehicle Parts & Services/Vehicle Parts & Accessories",
                    "Health/Medical Devices & Equipment",
                    "Shopping/Apparel",
                    "Online Communities/Social Networks",
                    "Computers & Electronics/Software",
                    "Health/Health Conditions/Cancer",
                    "Shopping",
                    "Arts & Entertainment/Humor",
                    "Arts & Entertainment",
                    "Arts & Entertainment/Comics & Animation/Cartoons",
                    "Travel/Tourist Destinations/Theme Parks",
                    "Science",
                    "Jobs & Education/Education/Primary & Secondary Schooling (K-12)",
                    "Internet & Telecom/Mobile & Wireless/Mobile Apps & Add-Ons",
                    "Business & Industrial/Transportation & Logistics",
                    "Health/Nursing/Assisted Living & Long Term Care",
                    "Science/Computer Science",
                    "Law & Government/Legal",
                    "Beauty & Fitness/Fitness",
                    "Food & Drink/Beverages/Soft Drinks",
                    "Real Estate",
                    "Arts & Entertainment/Music & Audio/Pop Music",
                    "News/Sports News",
                    "Law & Government/Social Services",
                    "Computers & Electronics/Computer Security",
                    "Arts & Entertainment/Music & Audio/Urban & Hip-Hop",
                    "Health/Pharmacy/Drugs & Medications",
                    "Travel",
                    "Arts & Entertainment/TV & Video",
                    "Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles",
                    "Law & Government/Public Safety",
                    "Arts & Entertainment/Comics & Animation/Comics",
                    "Science/Astronomy",
                    "Finance/Credit & Lending",
                    "Computers & Electronics/Computer Security/Hacking & Cracking",
                    "Arts & Entertainment/Music & Audio/Rock Music",
                    "Business & Industrial/Agriculture & Forestry/Livestock",
                    "Law & Government",
                    "Health/Public Health/Jobs & Education/Education/Colleges & Universities",
                    "Books & Literature/Children's Literature",
                    "Jobs & Education/Jobs/Job Listings",
                    "Computers & Electronics/Consumer Electronics/Game Systems & Consoles",
                    "People & Society/Family & Relationships",
                    "Arts & Entertainment/Music & Audio/Radio",
                    "Internet & Telecom/Mobile & Wireless",
                    "People & Society/Religion & Belief",
                    "Business & Industrial/Construction & Maintenance",
                    "Internet & Telecom",
                    "Business & Industrial/Business Finance/Venture Capital",
                    "Games/Computer & Video Games/Shooter Games",
                    "Food & Drink/Food & Grocery Retailers",
                    "Science/Mathematics",
                    "Business & Industrial/Aerospace & Defense/Space Technology",
                    "Computers & Electronics/Computer Hardware",
                    "Internet & Telecom/Email & Messaging",
                    "Business & Industrial/Hospitality Industry",
                    "People & Society/Social Sciences/Economics",
                    "Real Estate/Real Estate Listings/Lots & Land",
                    "Business & Industrial/Energy & Utilities/Renewable & Alternative Energy",
                    "Internet & Telecom/Service Providers",
                    "Law & Government/Military",
                    "Reference/Humanities/Philosophy",
                    "Law & Government/Public Safety/Law Enforcement",
                    "People & Society/Social Sciences/Political Science",
                    "Business & Industrial/Automotive Industry",
                    "Science/Biological Sciences",
                    "Business & Industrial/Chemicals Industry",
                    "Beauty & Fitness",
                    "Finance/Financial Planning & Management",
                    "Health/Reproductive Health",
                    "Business & Industrial/Agriculture & Forestry",
                    "Sports/Team Sports/Australian Football",
                    "Business & Industrial/Business Services/Consulting",
                    "Law & Government/Government/Visa & Immigration",
                    "Computers & Electronics/Electronics & Electrical/Power Supplies",
                    "Health/Health Conditions",
                    "Beauty & Fitness/Face & Body Care",
                    "Business & Industrial/Industrial Materials & Equipment",
                    "People & Society/Social Issues & Advocacy/Charity & Philanthropy",
                    "Business & Industrial/Business Operations",
                    "Business & Industrial/Hospitality Industry/Food Service",
                    "Internet & Telecom/Service Providers/Cable & Satellite Providers",
                    "Business & Industrial/Manufacturing",
                    "Internet & Telecom/Mobile & Wireless/Mobile Phones",
                    "Arts & Entertainment/Visual Art & Design/Art Museums & Galleries",
                    "Reference/Libraries & Museums/Museums",
                    "News/Weather",
                    "Travel/Car Rental & Taxi Services",
                    "Computers & Electronics/Enterprise Technology",
                    "Sports/Team Sports/American Football",
                    "Health/Health Conditions/Endocrine Conditions",
                    "Jobs & Education/Education/Standardized & Admissions Tests",
                    "Health/Health Conditions/Neurological Conditions",
                    "Sports/Team Sports",
                    "Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics",
                    "Business & Industrial/Printing & Publishing",
                    "Internet & Telecom/Web Services",
                    "Food & Drink/Food",
                    "Arts & Entertainment/Visual Art & Design/Painting",
                    "Finance/Accounting & Auditing/Tax Preparation & Planning",
                    "Business & Industrial/Industrial Materials & Equipment/Heavy Machinery",
                    "Health/Health Conditions/Genetic Disorders",
                    "Finance/Credit & Lending/Credit Reporting & Monitoring",
                    "Arts & Entertainment/Entertainment Industry",
                    "Reference",
                    "Computers & Electronics/Computer Hardware/Computer Drives & Storage",
                    "Travel/Hotels & Accommodations",
                    "Business & Industrial/Transportation & Logistics/Rail Transport",
                    "Food & Drink/Restaurants/Pizzerias",
                    "Health/Medical Facilities & Services/Medical Procedures",
                    "Business & Industrial/Energy & Utilities/Electricity",
                    "Business & Industrial/Transportation & Logistics/Freight & Trucking",
                    "Law & Government/Public Safety/Security Products & Services",
                    "People & Society/Seniors & Retirement",
                    "People & Society/Social Issues & Advocacy/Work & Labor Issues",
                    "Home & Garden/Home Furnishings",
                    "Science/Physics",
                    "Beauty & Fitness/Face & Body Care/Skin & Nail Care",
                    "Home & Garden/Home Furnishings/Living Room Furniture",
                    "Law & Government/Public Safety/Crime & Justice",
                    "Science/Earth Sciences/Geology",
                    "Autos & Vehicles/Vehicle Codes & Driving Laws",
                    "Computers & Electronics/Programming",
                    "Business & Industrial/Transportation & Logistics/Packaging",
                    "Health/Substance Abuse/Drug & Alcohol Treatment",
                    "Shopping/Auctions",
                    "Health/Pharmacy",
                    "Food & Drink/Restaurants/Fast Food",
                    "Games/Gambling",
                    "Shopping/Apparel/Clothing Accessories",
                    "Home & Garden/Gardening & Landscaping",
                    "Home & Garden/Home Improvement/Flooring",
                    "Computers & Electronics/Software/Software Utilities",
                    "Business & Industrial/Agriculture & Forestry/Agricultural Equipment",
                    "Health/Health Conditions/Pain Management",
                    "Shopping/Mass Merchants & Department Stores",
                    "Sports/Sporting Goods",
                    "Autos & Vehicles/Vehicle Shopping",
                    "Health/Medical Facilities & Services",
                    "Business & Industrial/Transportation & Logistics/Mail & Package Delivery",
                    "Real Estate/Real Estate Listings/Commercial Properties",
                    "Jobs & Education/Jobs",
                    "Health/Health Conditions/Heart & Hypertension",
                    "Shopping/Tobacco Products",
                    "Home & Garden/Home Improvement/Construction & Power Tools",
                    "Business & Industrial/Business Services/Office Supplies",
                    "Hobbies & Leisure",
                    "Finance/Credit & Lending/Credit Cards",
                    "Pets & Animals/Pets/Dogs",
                    "Health/Nutrition/Vitamins & Supplements",
                    "Business & Industrial/Chemicals Industry/Plastics & Polymers",
                    "Business & Industrial/Business Services/E-Commerce Services",
                    "Finance/Insurance/Health Insurance",
                    "Finance/Financial Planning & Management/Retirement & Pension",
                    "Real Estate/Real Estate Services",
                    "Health/Nutrition",
                    "Finance/Accounting & Auditing/Billing & Invoicing",
                    "Sports/Team Sports/Cricket",
                    "Jobs & Education",
                    "Home & Garden/Home Appliances",
                    "Shopping/Apparel/Athletic Apparel",
                    "Food & Drink/Beverages/Alcoholic Beverages",
                    "Real Estate/Real Estate Listings",
                    "Business & Industrial/Chemicals Industry/Cleaning Agents",
                    "Food & Drink/Food/Meat & Seafood",
                    "Real Estate/Real Estate Listings/Residential Sales",
                    "Beauty & Fitness/Face & Body Care/Perfumes & Fragrances",
                    "Business & Industrial/Metals & Mining/Precious Metals",
                    "Food & Drink/Food/Snack Foods",
                    "Computers & Electronics/Software/Multimedia Software",
                    "Computers & Electronics/Networking",
                    "Arts & Entertainment/Music & Audio/Music Equipment & Technology",
                    "Shopping/Toys",
                    "Arts & Entertainment/Entertainment Industry/Film & TV Industry",
                    "Arts & Entertainment/Entertainment Industry/Recording Industry",
                    "Pets & Animals/Animal Products & Services/Pet Food & Supplies",
                    "Jobs & Education/Education",
                    "Science/Earth Sciences",
                    "Science/Engineering & Technology",
                    "Home & Garden/Home Improvement",
                    "Computers & Electronics/Networking/VPN & Remote Access",
                    "Hobbies & Leisure/Water Activities/Boating",
                    "Arts & Entertainment/Visual Art & Design",
                    "Arts & Entertainment/Music & Audio/Classical Music",
                    "Home & Garden/Yard & Patio/Lawn Mowers",
                    "Sports/Individual Sports/Cycling",
                    "Computers & Electronics/Networking/Network Monitoring & Management"
            };

            Set<String> processedCategories = new HashSet<>();

            for (String category : categories) {
                String[] parts = category.split("/");
                if (parts.length > 1) {
                    processedCategories.add(parts[0]);
                }
            }

            List<String> sortedCategories = new ArrayList<>(processedCategories);
            Collections.sort(sortedCategories);

            for (String category : sortedCategories) {
                System.out.println(category);
            }
        }

}
